spring.application.name=ProjectionJPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/hospitalDB?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=Redx@0711
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql
server.port=9090